### ISSUE TITLE
Practica Métricas 

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-con-sonarcloud-team-remi#1]
[Práctica #1 - Unidad 2.pdf](https://github.com/SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-con-sonarcloud-team-remi/files/9669469/Practica.1.-.Unidad.2.pdf)

**Comment by bg55-a** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
